/*
 * WCSMosaicDialog.cpp
 *
 * Implementation of WCSMosaicDialog.
 *
 * Build overview
 * --------------
 * 1. The user selects two or more images from the list and chooses one as the
 *    reference anchor.
 * 2. onApply() calls buildMosaic(), which:
 *    a. Projects the four corners of every selected panel through the WCS of
 *       that panel into sky coordinates, then back into the pixel frame of
 *       the anchor. This establishes the bounding box of the full mosaic in
 *       anchor-pixel space.
 *    b. Allocates an output buffer sized to that bounding box and adjusts the
 *       anchor WCS (CRPIX) to account for the offset so the output carries a
 *       valid WCS solution.
 *    c. For every output pixel, converts anchor-pixel -> sky -> source-panel
 *       pixel using WCSUtils, samples the source with bilinear interpolation,
 *       and accumulates the weighted contribution into the output buffer. The
 *       per-pixel weight comes from a feathered blend mask generated by
 *       Stacking::Blending::generateBlendMask(). OpenMP is used to parallelise
 *       the per-panel reprojection loops.
 *    d. Divides each output pixel by the accumulated weight sum (normalisation)
 *       and returns the finished buffer.
 * 3. If buildMosaic() succeeds, mosaicReady() is emitted so the main window
 *    can open the result in a new viewer.
 */

#include "WCSMosaicDialog.h"
#include "../MainWindowCallbacks.h"
#include "../astrometry/WCSUtils.h"
#include "../stacking/Blending.h"
#include "../widgets/CustomMdiSubWindow.h"

#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QGroupBox>
#include <QListWidget>
#include <QComboBox>
#include <QSpinBox>
#include <QPushButton>
#include <QLabel>
#include <QMessageBox>
#include <QFormLayout>
#include <QCoreApplication>

#include <vector>
#include <cmath>
#include <algorithm>

#include <omp.h>


// ---------------------------------------------------------------------------
// Construction / destruction
// ---------------------------------------------------------------------------

WCSMosaicDialog::WCSMosaicDialog(QWidget* parent)
    : DialogBase(parent, tr("WCS Mosaic Builder"), 600, 450)
{
    setupUI();
}

WCSMosaicDialog::~WCSMosaicDialog()
{
    // Child widgets are owned by the Qt object tree; no manual cleanup needed.
}


// ---------------------------------------------------------------------------
// UI initialisation
// ---------------------------------------------------------------------------

void WCSMosaicDialog::setupUI()
{
    QVBoxLayout* mainLayout = new QVBoxLayout(this);
    mainLayout->setContentsMargins(15, 15, 15, 15);
    mainLayout->setSpacing(10);

    // Instructional text at the top of the dialog.
    QLabel* helpLabel = new QLabel(
        tr("Select multiple open images to stitch into a single mosaic. "
           "All selected images must have valid WCS astrometric solutions. "
           "The reference image anchors the final projection plane and pixel scale."),
        this
    );
    helpLabel->setWordWrap(true);
    mainLayout->addWidget(helpLabel);

    // Image selection list - allows the user to pick two or more panels.
    QGroupBox* imgGroup   = new QGroupBox(tr("Input Images"), this);
    QVBoxLayout* imgLayout = new QVBoxLayout(imgGroup);

    m_imageList = new QListWidget(this);
    m_imageList->setSelectionMode(QAbstractItemView::MultiSelection);
    connect(m_imageList, &QListWidget::itemSelectionChanged,
            this,        &WCSMosaicDialog::updateSelection);

    imgLayout->addWidget(m_imageList);
    mainLayout->addWidget(imgGroup);

    // Mosaic settings: reference anchor and feathering distance.
    QGroupBox*   settingsGroup = new QGroupBox(tr("Mosaic Settings"), this);
    QFormLayout* formLayout    = new QFormLayout(settingsGroup);

    m_referenceCombo = new QComboBox(this);
    formLayout->addRow(tr("Reference anchor:"), m_referenceCombo);

    m_featherSpin = new QSpinBox(this);
    m_featherSpin->setRange(0, 5000);
    m_featherSpin->setValue(100);
    m_featherSpin->setSuffix(tr(" px"));
    formLayout->addRow(tr("Feathering distance:"), m_featherSpin);

    mainLayout->addWidget(settingsGroup);

    // Status line showing the current selection count.
    m_statusLabel = new QLabel(tr("Ready"), this);
    mainLayout->addWidget(m_statusLabel);

    // Dialog action buttons.
    QHBoxLayout* btnLayout = new QHBoxLayout();
    m_btnApply  = new QPushButton(tr("Apply"),  this);
    m_btnCancel = new QPushButton(tr("Cancel"), this);

    connect(m_btnApply,  &QPushButton::clicked, this, &WCSMosaicDialog::onApply);
    connect(m_btnCancel, &QPushButton::clicked, this, &QDialog::reject);

    btnLayout->addStretch();
    btnLayout->addWidget(m_btnCancel);
    btnLayout->addWidget(m_btnApply);
    mainLayout->addLayout(btnLayout);

    // Reflect initial (empty) selection state.
    updateSelection();
}


// ---------------------------------------------------------------------------
// Public interface
// ---------------------------------------------------------------------------

void WCSMosaicDialog::setViewer(ImageViewer* v)
{
    m_activeViewer = v;
}

void WCSMosaicDialog::setAvailableImages(const QVector<ImageViewer*>& images)
{
    m_availableImages = images;
    m_imageList->clear();
    m_referenceCombo->clear();

    for (int i = 0; i < images.size(); ++i)
    {
        ImageViewer* v = images[i];

        // Skip null or uninitialised viewers.
        if (!v || !v->getBuffer().isValid())
            continue;

        // Only images with a valid WCS solution can participate in the mosaic.
        if (!WCSUtils::hasValidWCS(v->getBuffer().metadata()))
            continue;

        // Use the window title of the MDI sub-window if available.
        QString title;
        QWidget* p = v->parentWidget();
        while (p && !qobject_cast<CustomMdiSubWindow*>(p))
            p = p->parentWidget();

        if (p)
            title = p->windowTitle();
        else
            title = tr("Image %1").arg(i + 1);

        // Remove the modification marker '*' if present.
        if (title.endsWith('*'))
            title.chop(1);
        title = title.trimmed();

        QListWidgetItem* item = new QListWidgetItem(title, m_imageList);

        // Store the viewer pointer as opaque user data on the list item so it
        // can be retrieved without maintaining a separate index mapping.
        item->setData(Qt::UserRole, QVariant::fromValue(reinterpret_cast<void*>(v)));

        // Pre-select the currently active viewer.
        if (v == m_activeViewer)
            item->setSelected(true);
    }

    updateSelection();
}


// ---------------------------------------------------------------------------
// Private slots
// ---------------------------------------------------------------------------

void WCSMosaicDialog::updateSelection()
{
    // Rebuild the reference combo so it always reflects the current selection.
    m_referenceCombo->clear();
    int selectedCount = 0;

    for (int i = 0; i < m_imageList->count(); ++i)
    {
        QListWidgetItem* item = m_imageList->item(i);
        if (item->isSelected())
        {
            m_referenceCombo->addItem(item->text(), item->data(Qt::UserRole));
            ++selectedCount;
        }
    }

    // The mosaic requires at least two panels.
    m_btnApply->setEnabled(selectedCount >= 2);
    m_statusLabel->setText(
        tr("%1 images selected (requires at least 2)").arg(selectedCount)
    );
}

void WCSMosaicDialog::onApply()
{
    if (m_referenceCombo->count() < 2)
        return;

    ImageBuffer resultBuffer;
    QString     errorMsg;

    // Notify the main window that a long operation is starting so it can
    // update the UI appropriately (e.g. show a progress indicator).
    if (getCallbacks())
    {
        getCallbacks()->startLongProcess();
        getCallbacks()->logMessage(
            tr("Starting WCS Mosaic generation..."), 0
        );
    }

    m_btnApply->setEnabled(false);

    const bool ok = buildMosaic(resultBuffer, errorMsg);

    if (getCallbacks())
        getCallbacks()->endLongProcess();

    m_btnApply->setEnabled(true);

    if (!ok)
    {
        QMessageBox::critical(this, tr("Mosaic Error"), errorMsg);
        return;
    }

    if (getCallbacks())
    {
        getCallbacks()->logMessage(
            tr("WCS Mosaic successfully computed."), 1
        );
    }

    emit mosaicReady(resultBuffer, tr("Mosaic"));
}


// ---------------------------------------------------------------------------
// Core mosaic computation
// ---------------------------------------------------------------------------

bool WCSMosaicDialog::buildMosaic(ImageBuffer& outputBuffer, QString& errorMsg)
{
    // -----------------------------------------------------------------------
    // Step 1 - Collect selected viewers and resolve the anchor.
    // -----------------------------------------------------------------------

    std::vector<ImageViewer*> selected;
    ImageViewer* anchor = nullptr;

    for (int i = 0; i < m_imageList->count(); ++i)
    {
        QListWidgetItem* item = m_imageList->item(i);
        if (item->isSelected())
        {
            void* ptr = item->data(Qt::UserRole).value<void*>();
            ImageViewer* v = reinterpret_cast<ImageViewer*>(ptr);
            if (v)
                selected.push_back(v);
        }
    }

    if (m_referenceCombo->currentIndex() >= 0)
    {
        void* ptr = m_referenceCombo->currentData().value<void*>();
        anchor    = reinterpret_cast<ImageViewer*>(ptr);
    }

    if (!anchor || selected.size() < 2)
    {
        errorMsg = tr("Insufficient valid images or missing anchor.");
        return false;
    }

    const auto& anchorMeta = anchor->getBuffer().metadata();

    // -----------------------------------------------------------------------
    // Step 2 - Compute the output bounding box in anchor-pixel coordinates.
    //
    // Each panel's four corners are projected through its own WCS to sky
    // coordinates and then back into the anchor's pixel frame. The union of
    // all projected corners gives the extent of the full mosaic canvas.
    // -----------------------------------------------------------------------

    double minPx =  1e9, maxPx = -1e9;
    double minPy =  1e9, maxPy = -1e9;

    // Aggregate per-panel data needed during the reprojection pass.
    struct InputWCS
    {
        ImageViewer* v;
        ImageBuffer* mask;  // Heap-allocated; freed at the end of this function.
        double minx, maxx;  // Bounding box of this panel in anchor-pixel space,
        double miny, maxy;  // used for quick culling during reprojection.
    };

    std::vector<InputWCS> inputs;
    inputs.reserve(selected.size());

    for (ImageViewer* v : selected)
    {
        const auto& meta = v->getBuffer().metadata();
        const int   w    = v->getBuffer().width();
        const int   h    = v->getBuffer().height();

        // The four image corners in source-pixel coordinates.
        const double cornersX[4] = { 0.0, static_cast<double>(w), static_cast<double>(w), 0.0 };
        const double cornersY[4] = { 0.0, 0.0, static_cast<double>(h), static_cast<double>(h) };

        InputWCS iwcs;
        iwcs.v    = v;
        iwcs.minx =  1e9; iwcs.maxx = -1e9;
        iwcs.miny =  1e9; iwcs.maxy = -1e9;

        for (int i = 0; i < 4; ++i)
        {
            double ra, dec;
            if (!WCSUtils::pixelToWorld(meta, cornersX[i], cornersY[i], ra, dec))
                continue;

            double anchorPx, anchorPy;
            if (!WCSUtils::worldToPixel(anchorMeta, ra, dec, anchorPx, anchorPy))
                continue;

            // Global canvas extents.
            minPx = std::min(minPx, anchorPx);
            maxPx = std::max(maxPx, anchorPx);
            minPy = std::min(minPy, anchorPy);
            maxPy = std::max(maxPy, anchorPy);

            // Per-panel extents for bounding-box culling.
            iwcs.minx = std::min(iwcs.minx, anchorPx);
            iwcs.maxx = std::max(iwcs.maxx, anchorPx);
            iwcs.miny = std::min(iwcs.miny, anchorPy);
            iwcs.maxy = std::max(iwcs.maxy, anchorPy);
        }

        // Generate a feathered blend mask for this panel.
        std::vector<float> maskData;
        Stacking::Blending::generateBlendMask(v->getBuffer(), m_featherSpin->value(), maskData);

        ImageBuffer* mBuf = new ImageBuffer();
        mBuf->setData(w, h, 1, maskData);
        iwcs.mask = mBuf;

        inputs.push_back(iwcs);
    }

    // Add a small safety margin around the canvas to avoid clipping pixels
    // that land exactly on the computed boundary.
    minPx -= 10.0;  maxPx += 10.0;
    minPy -= 10.0;  maxPy += 10.0;

    const int outW = static_cast<int>(std::ceil(maxPx - minPx));
    const int outH = static_cast<int>(std::ceil(maxPy - minPy));

    // Sanity-check the canvas dimensions before allocating memory.
    if (outW <= 0 || outH <= 0 || outW > 30000 || outH > 30000)
    {
        errorMsg = tr(
            "Resulting mosaic dimensions (%1x%2) are invalid or excessively large. Check WCS data."
        ).arg(outW).arg(outH);

        for (auto& iw : inputs)
            delete iw.mask;

        return false;
    }

    // -----------------------------------------------------------------------
    // Step 3 - Set up the output WCS metadata.
    //
    // The output projection is identical to the anchor's WCS except that
    // CRPIX is shifted to account for the canvas offset introduced by the
    // bounding-box expansion (minPx, minPy).
    // -----------------------------------------------------------------------

    ImageBuffer::Metadata newMeta = anchorMeta;
    newMeta.crpix1 -= minPx;
    newMeta.crpix2 -= minPy;

    // -----------------------------------------------------------------------
    // Step 4 - Allocate the output canvas and accumulation buffers.
    // -----------------------------------------------------------------------

    const int channels = anchor->getBuffer().channels();
    outputBuffer.resize(outW, outH, channels);
    outputBuffer.metadata() = newMeta;

    std::vector<float>& outData = outputBuffer.data();
    std::fill(outData.begin(), outData.end(), 0.0f);

    // Per-pixel accumulated weight (sum of blend-mask values across all panels
    // that contributed to that pixel; used to normalise the final colour).
    std::vector<float> weightMap(outW * outH, 0.0f);

    // -----------------------------------------------------------------------
    // Step 5 - WCS reprojection and feathered blending.
    //
    // For every output pixel we perform:
    //   output pixel (x, y)
    //       -> anchor pixel coordinate (destPx, destPy)
    //       -> sky (RA, Dec)  [via anchor WCS]
    //       -> source pixel (px, py)  [via source WCS]
    //       -> bilinear sample of source colour and blend weight
    //       -> weighted accumulation into outData / weightMap
    //
    // The inner loops are parallelised with OpenMP across (y, x) pairs.
    // The atomic updates are required because multiple panels may contribute
    // to the same output pixel.
    // -----------------------------------------------------------------------

    bool aborted = false;

    for (size_t i = 0; i < inputs.size(); ++i)
    {
        if (aborted)
            break;

        auto&              iwcs    = inputs[i];
        const ImageBuffer& srcBuf  = iwcs.v->getBuffer();
        const auto&        srcMeta = srcBuf.metadata();

        const int srcW    = srcBuf.width();
        const int srcH    = srcBuf.height();
        const int srcChans = srcBuf.channels();

        if (getCallbacks())
        {
            QString title;
            QWidget* p = iwcs.v->parentWidget();
            while (p && !qobject_cast<CustomMdiSubWindow*>(p))
                p = p->parentWidget();

            if (p) {
                title = p->windowTitle();
                if (title.endsWith('*')) title.chop(1);
                title = title.trimmed();
            } else {
                title = tr("panel");
            }

            getCallbacks()->logMessage(
                tr("Blending panel %1...").arg(title), 0
            );
        }

        #pragma omp parallel for collapse(2) shared(aborted)
        for (int y = 0; y < outH; ++y)
        {
            for (int x = 0; x < outW; ++x)
            {
                if (aborted)
                    continue;

                // Map output canvas pixel back to anchor-frame coordinates.
                const double destPx = x + minPx;
                const double destPy = y + minPy;

                // Coarse bounding-box cull: skip pixels that are clearly
                // outside this panel's projected footprint (with 50 px slack
                // to handle reprojection distortion near panel edges).
                if (destPx < iwcs.minx - 50.0 || destPx > iwcs.maxx + 50.0 ||
                    destPy < iwcs.miny - 50.0 || destPy > iwcs.maxy + 50.0)
                    continue;

                // Anchor pixel -> sky.
                double ra, dec;
                if (!WCSUtils::pixelToWorld(anchorMeta, destPx, destPy, ra, dec))
                    continue;

                // Sky -> source panel pixel.
                double px, py;
                if (!WCSUtils::worldToPixel(srcMeta, ra, dec, px, py))
                    continue;

                // Only process coordinates that fall strictly inside the source
                // image (leaving a one-pixel border for bilinear interpolation).
                if (px < 0.0 || px >= srcW - 1 || py < 0.0 || py >= srcH - 1)
                    continue;

                // Bilinear interpolation weights.
                const int   x0  = static_cast<int>(px);
                const int   y0  = static_cast<int>(py);
                const int   x1  = x0 + 1;
                const int   y1  = y0 + 1;
                const float dx  = static_cast<float>(px - x0);
                const float dy  = static_cast<float>(py - y0);
                const float dx1 = 1.0f - dx;
                const float dy1 = 1.0f - dy;

                // Reusable bilinear sampler for any planar data buffer.
                auto sampleBilinear = [&](const std::vector<float>& data,
                                          int w, int c, int nChans) -> float
                {
                    const float v00 = data[(y0 * w + x0) * nChans + c];
                    const float v10 = data[(y0 * w + x1) * nChans + c];
                    const float v01 = data[(y1 * w + x0) * nChans + c];
                    const float v11 = data[(y1 * w + x1) * nChans + c];
                    return dy1 * (dx1 * v00 + dx * v10)
                         + dy  * (dx1 * v01 + dx * v11);
                };

                // Sample the blend weight from the pre-generated mask.
                const float weight = sampleBilinear(iwcs.mask->data(), srcW, 0, 1);

                if (weight <= 0.0f)
                    continue;

                // Accumulate weighted colour contribution for each channel.
                for (int c = 0; c < channels; ++c)
                {
                    // Clamp the source channel index in case the source has
                    // fewer channels than the output (e.g. mono vs. colour).
                    const int   sc  = std::min(c, srcChans - 1);
                    const float val = sampleBilinear(srcBuf.data(), srcW, sc, srcChans);

                    #pragma omp atomic
                    outData[(y * outW + x) * channels + c] += val * weight;
                }

                #pragma omp atomic
                weightMap[y * outW + x] += weight;
            }
        }
    }

    // -----------------------------------------------------------------------
    // Step 6 - Normalise the output by the accumulated weight map.
    //
    // Pixels with zero total weight (not covered by any panel) are set to
    // black. All others are divided by their total weight to produce the
    // correctly blended colour value.
    // -----------------------------------------------------------------------

    #pragma omp parallel for collapse(2)
    for (int y = 0; y < outH; ++y)
    {
        for (int x = 0; x < outW; ++x)
        {
            const float tw = weightMap[y * outW + x];

            if (tw > 0.0f)
            {
                for (int c = 0; c < channels; ++c)
                    outData[(y * outW + x) * channels + c] /= tw;
            }
            else
            {
                for (int c = 0; c < channels; ++c)
                    outData[(y * outW + x) * channels + c] = 0.0f;
            }
        }
    }

    // -----------------------------------------------------------------------
    // Step 7 - Release dynamically allocated blend mask buffers.
    // -----------------------------------------------------------------------

    for (auto& iw : inputs)
        delete iw.mask;

    return true;
}